sudo: required
services:
  - docker

before_install:
  - docker build -t arvindcs12/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true arvindcs12/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-661063546507"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


